//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoolWallet.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CoolWallet.Core.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checksum Exception: Provided parts are corrupt or incomplete..
        /// </summary>
        public static string ChecksumExceptionSharesCorrupt {
            get {
                return ResourceManager.GetString("ChecksumExceptionSharesCorrupt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data should not be null or empty..
        /// </summary>
        public static string DataIsNullOrEmpty {
            get {
                return ResourceManager.GetString("DataIsNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough unique parts to get the private key..
        /// </summary>
        public static string NotEnoughShares {
            get {
                return ResourceManager.GetString("NotEnoughShares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All provided parts must have the same signature..
        /// </summary>
        public static string SharesHaveDifferentSignatures {
            get {
                return ResourceManager.GetString("SharesHaveDifferentSignatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The threshold number of parts cannot be less than one..
        /// </summary>
        public static string SharesThresholdCannotBeLessThanOne {
            get {
                return ResourceManager.GetString("SharesThresholdCannotBeLessThanOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The threshold number of parts cannot be less than the total number of shares..
        /// </summary>
        public static string SharesThresholdCannotBeLessThanSharesTotal {
            get {
                return ResourceManager.GetString("SharesThresholdCannotBeLessThanSharesTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The total number of parts cannot be less than one..
        /// </summary>
        public static string SharesTotalCannotBeLessThanOne {
            get {
                return ResourceManager.GetString("SharesTotalCannotBeLessThanOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature cannot be null..
        /// </summary>
        public static string SignatureIsNull {
            get {
                return ResourceManager.GetString("SignatureIsNull", resourceCulture);
            }
        }
    }
}
